### ISSUE TITLE
Integrate/steal/whatever domain-enforcer

### ISSUE THREAD

**Issue by theangrydev** [tjheslin1/Westie#2]
The thing we use for our DDD packages, [domain-enforcer](https://github.com/theangrydev/domain-enforcer), is very similar to the `ImportsRestrictionChecker`.

Feel free to add it as a transitive dependency of Westie, or steal bits of code or whatever from it. Just thought I'd let you know so we don't both duplicate our efforts :)

**Comment by tjheslin1** [comment]
Yep, completely agree. I'm happy to remove the Checker and recommend domain-enforcer if this functionality is requested?

**Comment by tjheslin1** [comment]
`ImportsRestrictionChecker` has been deprecated in favour of [domain-enforcer](https://github.com/theangrydev/domain-enforcer) in [1.1.3](https://github.com/tjheslin1/Westie/releases/tag/1.1.3)
