### ISSUE TITLE
Allow empty files

### ISSUE THREAD

**Issue by theangrydev** [tjheslin1/Westie#7]
Hi Tom,

I hope you are doing well.

I have a project with quite a few intentionally empty files and so I would like to either remove the check for an empty file or at least make it configurable:
`Empty file! - Should this file be in the list of ignored files? Or in a different directory?`

It would be too cumbersome to add each file to the excludes list.

Hope this makes sense, let me know what you think.

**Comment by tjheslin1** [comment]
Addressed in version [1.4.3](https://github.com/tjheslin1/Westie/releases/tag/1.4.3)
